SET ROLE hugo;


INSERT INTO Finalists (category, sortindex, title, subtitle) VALUES
('Novel',1,'The Calculating Stars','by Mary Robinette Kowal (Tor)'),
('Novel',2,'Record of a Spaceborn Few','by Becky Chambers (Hodder & Stoughton / Harper Voyager)'),
('Novel',3,'Revenant Gun','by Yoon Ha Lee (Solaris)'),
('Novel',4,'Space Opera','by Catherynne M. Valente (Saga)'),
('Novel',5,'Spinning Silver','by Naomi Novik (Del Rey / Macmillan)'),
('Novel',6,'Trail of Lightning','by Rebecca Roanhorse (Saga)'),
('Novella',1,'Artificial Condition','by Martha Wells (Tor.com publishing)'),
('Novella',2,'Beneath the Sugar Sky','by Seanan McGuire (Tor.com publishing)'),
('Novella',3,'Binti: The Night Masquerade','by Nnedi Okorafor (Tor.com publishing)'),
('Novella',4,'The Black God’s Drums','by P. Djèlí Clark (Tor.com publishing)'),
('Novella',5,'Gods, Monsters, and the Lucky Peach','by Kelly Robson (Tor.com publishing)'),
('Novella',6,'The Tea Master and the Detective','by Aliette de Bodard (Subterranean Press / JABberwocky Literary Agency)'),
('Novelette',1,'“If at First You Don’t Succeed, Try, Try Again”','by Zen Cho (B&N Sci-Fi and Fantasy Blog, 29 November 2018)'),
('Novelette',2,'“The Last Banquet of Temporal Confections”','by Tina Connolly (Tor.com, 11 July 2018)'),
('Novelette',3,'“Nine Last Days on Planet Earth”','by Daryl Gregory (Tor.com, 19 September 2018)'),
('Novelette',4,'The Only Harmless Great Thing','by Brooke Bolander (Tor.com publishing)'),
('Novelette',5,'“The Thing About Ghost Stories”','by Naomi Kritzer (Uncanny Magazine 25, November-December 2018)'),
('Novelette',6,'“When We Were Starless”','by Simone Heller (Clarkesworld 145, October 2018)'),
('ShortStory',1,'“The Court Magician”','by Sarah Pinsker (Lightspeed, January 2018)'),
('ShortStory',2,'“The Rose MacGregor Drinking and Admiration Society”','by T. Kingfisher (Uncanny Magazine 25, November-December 2018)'),
('ShortStory',3,'“The Secret Lives of the Nine Negro Teeth of George Washington”','by P. Djèlí Clark (Fireside Magazine, February 2018)'),
('ShortStory',4,'“STET”','by Sarah Gailey (Fireside Magazine, October 2018)'),
('ShortStory',5,'“The Tale of the Three Beautiful Raptor Sisters, and the Prince Who Was Made of Meat”','by Brooke Bolander (Uncanny Magazine 23, July-August 2018)'),
('ShortStory',6,'“A Witch’s Guide to Escape: A Practical Compendium of Portal Fantasies”','by Alix E. Harrow (Apex Magazine, February 2018)'),
('RelatedWork',1,'Archive of Our Own','a project of the Organization for Transformative Works'),
('RelatedWork',2,'Astounding: John W. Campbell, Isaac Asimov, Robert A. Heinlein, L. Ron Hubbard, and the Golden Age of Science Fiction','by Alec Nevala-Lee (Dey Street Books)'),
('RelatedWork',3,'The Hobbit Duology (documentary in three parts)','written and edited by Lindsay Ellis and Angelina Meehan (YouTube)'),
('RelatedWork',4,'An Informal History of the Hugos: A Personal Look Back at the Hugo Awards','1953-2000, by Jo Walton (Tor)'),
('RelatedWork',5,'www.mexicanxinitiative.com: The Mexicanx Initiative Experience at Worldcon 76','(Julia Rios, Libia Brenda, Pablo Defendini, John Picacio)'),
('RelatedWork',6,'Ursula K. Le Guin: Conversations on Writing','by Ursula K. Le Guin with David Naimon (Tin House Books)'),
('GraphicStory',1,'Abbott','written by Saladin Ahmed, art by Sami Kivelä, colours by Jason Wordie, letters by Jim Campbell (BOOM! Studios)'),
('GraphicStory',2,'Black Panther: Long Live the King','written by Nnedi Okorafor and Aaron Covington, art by André Lima Araújo, Mario Del Pennino and Tana Ford (Marvel)'),
('GraphicStory',3,'Monstress, Volume 3: Haven','written by Marjorie Liu, art by Sana Takeda (Image Comics)'),
('GraphicStory',4,'On a Sunbeam','by Tillie Walden (First Second)'),
('GraphicStory',5,'Paper Girls, Volume 4','written by Brian K. Vaughan, art by Cliff Chiang, colours by Matt Wilson, letters by Jared K. Fletcher (Image Comics)'),
('GraphicStory',6,'Saga, Volume 9','written by Brian K. Vaughan, art by Fiona Staples (Image Comics)'),
('DramaticLong',1,'Annihilation','directed and written for the screen by Alex Garland, based on the novel by Jeff VanderMeer (Paramount Pictures / Skydance)'),
('DramaticLong',2,'Avengers: Infinity War','screenplay by Christopher Markus and Stephen McFeely, directed by Anthony Russo and Joe Russo (Marvel Studios)'),
('DramaticLong',3,'Black Panther','written by Ryan Coogler and Joe Robert Cole, directed by Ryan Coogler (Marvel Studios)'),
('DramaticLong',4,'A Quiet Place','screenplay by Scott Beck, John Krasinski and Bryan Woods, directed by John Krasinski (Platinum Dunes / Sunday Night)'),
('DramaticLong',5,'Sorry to Bother You','written and directed by Boots Riley (Annapurna Pictures)'),
('DramaticLong',6,'Spider-Man: Into the Spider-Verse','screenplay by Phil Lord and Rodney Rothman, directed by Bob Persichetti, Peter Ramsey and Rodney Rothman (Sony)'),
('DramaticShort',1,'The Expanse: “Abaddon’s Gate”','written by Daniel Abraham, Ty Franck and Naren Shankar, directed by Simon Cellan Jones (Penguin in a Parka / Alcon Entertainment)'),
('DramaticShort',2,'Doctor Who: “Demons of the Punjab”','written by Vinay Patel, directed by Jamie Childs (BBC)'),
('DramaticShort',3,'Dirty Computer','written by Janelle Monáe and Chuck Lightning, directed by Andrew Donoho and Chuck Lightning (Wondaland Arts Society / Bad Boy Records / Atlantic Records)'),
('DramaticShort',4,'The Good Place: “Janet(s)”','written by Josh Siegal & Dylan Morgan, directed by Morgan Sackett (NBC)'),
('DramaticShort',5,'The Good Place: “Jeremy Bearimy”','written by Megan Amram, directed by Trent O’Donnell (NBC)'),
('DramaticShort',6,'Doctor Who: “Rosa”','written by Malorie Blackman and Chris Chibnall, directed by Mark Tonderai (BBC)'),
('EditorShort',1,'Neil Clarke',null),
('EditorShort',2,'Gardner Dozois',null),
('EditorShort',3,'Lee Harris',null),
('EditorShort',4,'Julia Rios',null),
('EditorShort',5,'Lynne M. Thomas and Michael Damian Thomas',null),
('EditorShort',6,'E. Catherine Tobler',null),
('EditorLong',1,'Sheila E. Gilbert',null),
('EditorLong',2,'Anne Lesley Groell',null),
('EditorLong',3,'Beth Meacham',null),
('EditorLong',4,'Diana Pho',null),
('EditorLong',5,'Gillian Redfearn',null),
('EditorLong',6,'Navah Wolfe',null),
('ProArtist',1,'Galen Dara',null),
('ProArtist',2,'Jaime Jones',null),
('ProArtist',3,'Victo Ngai',null),
('ProArtist',4,'John Picacio',null),
('ProArtist',5,'Yuko Shimizu',null),
('ProArtist',6,'Charles Vess',null),
('Semiprozine',1,'Beneath Ceaseless Skies','editor-in-chief and publisher Scott H. Andrews'),
('Semiprozine',2,'Fireside Magazine','edited by Julia Rios, managing editor Elsa Sjunneson-Henry, copyeditor Chelle Parker, social coordinator Meg Frank, special features editor Tanya DePass, founding editor Brian White, publisher and art director Pablo Defendini'),
('Semiprozine',3,'FIYAH Magazine of Black Speculative Fiction','executive editors Troy L. Wiggins and DaVaun Sanders, editors L.D. Lewis, Brandon O’Brien, Kaleb Russell, Danny Lore, and Brent Lambert'),
('Semiprozine',4,'Shimmer','publisher Beth Wodzinski, senior editor E. Catherine Tobler'),
('Semiprozine',5,'Strange Horizons','edited by Jane Crowley, Kate Dollarhyde, Vanessa Rose Phin, Vajra Chandrasekera, Romie Stott, Maureen Kincaid Speller, and the Strange Horizons Staff'),
('Semiprozine',6,'Uncanny Magazine','publishers/editors-in-chief Lynne M. Thomas and Michael Damian Thomas, managing editor Michi Trota, podcast producers Erika Ensign and Steven Schapansky, Disabled People Destroy Science Fiction Special Issue editors-in-chief Elsa Sjunneson-Henry and Dominik Parisien'),
('Fanzine',1,'Galactic Journey','founder Gideon Marcus, editor Janice Marcus'),
('Fanzine',2,'Journey Planet','edited by Team Journey Planet'),
('Fanzine',3,'Lady Business','editors Ira, Jodie, KJ, Renay & Susan'),
('Fanzine',4,'nerds of a feather, flock together','editors Joe Sherry, Vance Kotrla and The G'),
('Fanzine',5,'Quick Sip Reviews','editor Charles Payseur'),
('Fanzine',6,'Rocket Stack Rank','editors Greg Hullender and Eric Wong'),
('Fancast',1,'Be the Serpent','presented by Alexandra Rowland, Freya Marske and Jennifer Mace'),
('Fancast',2,'The Coode Street Podcast','presented by Jonathan Strahan and Gary K. Wolfe'),
('Fancast',3,'Fangirl Happy Hour','hosted by Ana Grilo and Renay Williams'),
('Fancast',4,'Galactic Suburbia','hosted by Alisa Krasnostein, Alexandra Pierce, and Tansy Rayner Roberts, produced by Andrew Finch'),
('Fancast',5,'Our Opinions Are Correct','hosted by Annalee Newitz and Charlie Jane Anders'),
('Fancast',6,'The Skiffy and Fanty Show','produced by Jen Zink and Shaun Duke, hosted by the Skiffy and Fanty Crew'),
('FanWriter',1,'Foz Meadows',null),
('FanWriter',2,'James Davis Nicoll',null),
('FanWriter',3,'Charles Payseur',null),
('FanWriter',4,'Elsa Sjunneson-Henry',null),
('FanWriter',5,'Alasdair Stuart',null),
('FanWriter',6,'Bogi Takács',null),
('FanArtist',1,'Sara Felix',null),
('FanArtist',2,'Grace P. Fong',null),
('FanArtist',3,'Meg Frank',null),
('FanArtist',4,'Ariela Housman',null),
('FanArtist',5,'Likhain (Mia Sereno)',null),
('FanArtist',6,'Spring Schoenhuth',null),
('Series',1,'The Centenal Cycle','by Malka Older (Tor.com publishing)'),
('Series',2,'The Laundry Files','by Charles Stross (most recently Tor.com publishing/Orbit)'),
('Series',3,'Machineries of Empire','by Yoon Ha Lee (Solaris)'),
('Series',4,'The October Daye Series','by Seanan McGuire (most recently DAW)'),
('Series',5,'The Universe of Xuya','by Aliette de Bodard (most recently Subterranean Press)'),
('Series',6,'Wayfarers','by Becky Chambers (Hodder & Stoughton / Harper Voyager)'),
('BestArtBook',1,'The Books of Earthsea: The Complete Illustrated Edition','illustrated by Charles Vess, written by Ursula K. Le Guin (Saga Press /Gollancz)'),
('BestArtBook',2,'Daydreamer’s Journey: The Art of Julie Dillon','by Julie Dillon (self-published)'),
('BestArtBook',3,'Dungeons & Dragons Art & Arcana: A Visual History','by Michael Witwer, Kyle Newman, Jon Peterson, Sam Witwer (Ten Speed Press)'),
('BestArtBook',4,'Spectrum 25: The Best in Contemporary Fantastic Art','ed. John Fleskes (Flesk Publications)'),
('BestArtBook',5,'Spider-Man: Into the Spider-Verse – The Art of the Movie','by Ramin Zahed (Titan Books)'),
('BestArtBook',6,'Tolkien: Maker of Middle-earth','ed. Catherine McIlwaine (Bodleian Library)'),
('Lodestar',1,'The Belles','by Dhonielle Clayton (Freeform / Gollancz)'),
('Lodestar',2,'Children of Blood and Bone','by Tomi Adeyemi (Henry Holt / Macmillan Children’s Books)'),
('Lodestar',3,'The Cruel Prince','by Holly Black (Little, Brown / Hot Key Books)'),
('Lodestar',4,'Dread Nation','by Justina Ireland (Balzer + Bray)'),
('Lodestar',5,'The Invasion','by Peadar O’Guilin (David Fickling Books / Scholastic)'),
('Lodestar',6,'Tess of the Road','by Rachel Hartman (Random House / Penguin Teen)'),
('NewWriter',1,'Katherine Arden','2nd year of eligibility'),
('NewWriter',2,'S.A. Chakraborty','2nd year of eligibility'),
('NewWriter',3,'R.F. Kuang','1st year of eligibility'),
('NewWriter',4,'Jeannette Ng','2nd year of eligibility'),
('NewWriter',5,'Vina Jie-Min Prasad','2nd year of eligibility'),
('NewWriter',6,'Rivers Solomon','2nd year of eligibility'),
('RetroNovel',1,'Conjure Wife','by Fritz Leiber, Jr. (Unknown Worlds, April 1943)'),
('RetroNovel',2,'Earth’s Last Citadel','by C.L. Moore and Henry Kuttner (Argosy, April 1943)'),
('RetroNovel',3,'Gather, Darkness!','by Fritz Leiber, Jr. (Astounding Science-Fiction, May-July 1943)'),
('RetroNovel',4,'Das Glasperlenspiel [The Glass Bead Game]','by Hermann Hesse (Fretz & Wasmuth)'),
('RetroNovel',5,'Perelandra','by C.S. Lewis (John Lane, The Bodley Head)'),
('RetroNovel',6,'The Weapon Makers','by A.E. van Vogt (Astounding Science-Fiction, February-April 1943)'),
('RetroNovella',1,'“Attitude”','by Hal Clement (Astounding Science-Fiction, September 1943)'),
('RetroNovella',2,'“Clash by Night”','by Lawrence O’Donnell (Henry Kuttner & C.L. Moore) (Astounding Science-Fiction, March 1943)'),
('RetroNovella',3,'“The Dream-Quest of Unknown Kadath”','by H.P. Lovecraft, (Beyond the Wall of Sleep, Arkham House)'),
('RetroNovella',4,'The Little Prince','by Antoine de Saint-Exupéry (Reynal & Hitchcock)'),
('RetroNovella',5,'The Magic Bed-Knob; or, How to Become a Witch in Ten Easy Lessons','by Mary Norton (Hyperion Press)'),
('RetroNovella',6,'“We Print the Truth”','by Anthony Boucher (Astounding Science-Fiction, December 1943)'),
('RetroNovelette',1,'“Citadel of Lost Ships”','by Leigh Brackett (Planet Stories, March 1943)'),
('RetroNovelette',2,'“The Halfling”','by Leigh Brackett (Astonishing Stories, February 1943)'),
('RetroNovelette',3,'“Mimsy Were the Borogoves”','by Lewis Padgett (C.L. Moore & Henry Kuttner) (Astounding Science-Fiction, February 1943)'),
('RetroNovelette',4,'“The Proud Robot”','by Lewis Padgett (Henry Kuttner) (Astounding Science-Fiction, February 1943)'),
('RetroNovelette',5,'“Symbiotica”','by Eric Frank Russell (Astounding Science-Fiction, October 1943)'),
('RetroNovelette',6,'“Thieves’ House”','by Fritz Leiber, Jr (Unknown Worlds, February 1943)'),
('RetroShortStory',1,'“Death Sentence”','by Isaac Asimov (Astounding Science Fiction, November 1943)'),
('RetroShortStory',2,'“Doorway into Time”','by C.L. Moore (Famous Fantastic Mysteries, September 1943)'),
('RetroShortStory',3,'“Exile”','by Edmond Hamilton (Super Science Stories, May 1943)'),
('RetroShortStory',4,'“King of the Gray Spaces” (“R is for Rocket”)','by Ray Bradbury (Famous Fantastic Mysteries, December 1943)'),
('RetroShortStory',5,'“Q.U.R.”','by H.H. Holmes (Anthony Boucher) (Astounding Science-Fiction, March 1943)'),
('RetroShortStory',6,'“Yours Truly – Jack the Ripper”','by Robert Bloch (Weird Tales, July 1943)'),
('RetroGraphicStory',1,'Buck Rogers: Martians Invade Jupiter','by Philip Nowlan and Dick Calkins (National Newspaper Service)'),
('RetroGraphicStory',2,'Flash Gordon: Fiery Desert of Mongo','by Alex Raymond (King Features Syndicate)'),
('RetroGraphicStory',3,'Garth','by Steve Dowling (Daily Mirror)'),
('RetroGraphicStory',4,'Plastic Man #1: The Game of Death','by Jack Cole (Vital Publications)'),
('RetroGraphicStory',5,'Le Secret de la Licorne [The Secret of the Unicorn]','by Hergé (Le Soir)'),
('RetroGraphicStory',6,'Wonder Woman #5: Battle for Womanhood','written by William Moulton Marsden, art by Harry G. Peter (DC Comics)'),
('RetroDramaticLong',1,'Batman','written by Victor McLeod, Leslie Swabacker and Harry L. Fraser, directed by Lambert Hillyer (Columbia Pictures)'),
('RetroDramaticLong',2,'Cabin in the Sky','written by Joseph Schrank, directed by Vincente Minnelli and Busby Berkeley (uncredited) (MGM)'),
('RetroDramaticLong',3,'A Guy Named Joe','written by Frederick Hazlitt Brennan and Dalton Trumbo, directed by Victor Fleming (MGM)'),
('RetroDramaticLong',4,'Heaven Can Wait','written by Samson Raphaelson, directed by Ernst Lubitsch (20th Century Fox)'),
('RetroDramaticLong',5,'Münchhausen','written by Erich Kästner and Rudolph Erich Raspe, directed by Josef von Báky (UFA)'),
('RetroDramaticLong',6,'Phantom of the Opera','written by Eric Taylor, Samuel Hoffenstein and Hans Jacoby, directed by Arthur Lubin (Universal Pictures)'),
('RetroDramaticShort',1,'The Ape Man','written by Barney A. Sarecky, directed by William Beaudine (Banner Productions)'),
('RetroDramaticShort',2,'Frankenstein Meets the Wolfman','written by Curt Siodmak, directed by Roy William Neill (Universal Pictures)'),
('RetroDramaticShort',3,'Der Fuehrer’s Face','story by Joe Grant and Dick Huemer, directed by Jack Kinney (Disney)'),
('RetroDramaticShort',4,'I Walked With a Zombie','written by Curt Siodmak and Ardel Wray, directed by Jacques Tourneur (RKO Radio Pictures)'),
('RetroDramaticShort',5,'The Seventh Victim','written by Charles O’Neal and DeWitt Bodeen, directed by Mark Robson (RKO Radio Pictures)'),
('RetroDramaticShort',6,'Super-Rabbit','written by Tedd Pierce, directed by Charles M. Jones (Warner Bros)'),
('RetroEditorShort',1,'John W. Campbell',null),
('RetroEditorShort',2,'Oscar J. Friend',null),
('RetroEditorShort',3,'Mary Gnaedinger',null),
('RetroEditorShort',4,'Dorothy McIlwraith',null),
('RetroEditorShort',5,'Raymond A. Palmer',null),
('RetroEditorShort',6,'Donald A. Wollheim',null),
('RetroProArtist',1,'Hannes Bok',null),
('RetroProArtist',2,'Margaret Brundage',null),
('RetroProArtist',3,'Virgil Finlay',null),
('RetroProArtist',4,'Antoine de Saint-Exupéry',null),
('RetroProArtist',5,'J. Allen St. John',null),
('RetroProArtist',6,'William Timmins',null),
('RetroFanzine',1,'Fantasy News','editor William S. Sykora'),
('RetroFanzine',2,'Futurian War Digest','editor J. Michael Rosenblum'),
('RetroFanzine',3,'The Phantagraph','editor Donald A. Wollheim'),
('RetroFanzine',4,'Voice of the Imagi-Nation','editors Jack Erman (Forrest J Ackerman) & Morojo (Myrtle Douglas)'),
('RetroFanzine',5,'YHOS','editor Art Widner'),
('RetroFanzine',6,'Le Zombie','editor Wilson “Bob” Tucker'),
('RetroFanWriter',1,'Forrest J. Ackerman',null),
('RetroFanWriter',2,'Morojo (Myrtle Douglas)',null),
('RetroFanWriter',3,'Jack Speer',null),
('RetroFanWriter',4,'Wilson “Bob” Tucker',null),
('RetroFanWriter',5,'Art Widner',null),
('RetroFanWriter',6,'Donald A. Wollheim',null);
