SET ROLE hugo;

INSERT INTO Finalists (competition, category, sortindex, title, subtitle) VALUES
('Hugos','Novel',1,'All the Birds in the Sea','by Charlie Jane Anders (Tor Books / Titan Books)'),
('Hugos','Novel',2,'A Closed and Common Orbit','by Becky Chambers (Hodder & Stoughton / Harper Voyager US)'),
('Hugos','Novel',3,'Death''s End','by Cixin Liu, translated by Ken Liu (Tor Books / Head of Zeus)'),
('Hugos','Novel',4,'Ninefox Gambit','by Yoon Ha Lee (Solaris Books)'),
('Hugos','Novel',5,'The Obelisk Gate','by N. K. Jemisin (Orbit Books)'),
('Hugos','Novel',6,'Too Like the Lightning','by Ada Palmer (Tor Books)'),
('Hugos','Novella',1,'The Ballad of Black Tom','by Victor LaValle (Tor.com publishing)'),
('Hugos','Novella',2,'The Dream-Quest of Vellitt Boe','by Kij Johnson (Tor.com publishing)'),
('Hugos','Novella',3,'Every Heart a Doorway','by Seanan McGuire (Tor.com publishing)'),
('Hugos','Novella',4,'Penric and the Shaman','by Lois McMaster Bujold (Spectrum Literary Agency)'),
('Hugos','Novella',5,'A Taste of Honey','by Kai Ashante Wilson (Tor.com publishing)'),
('Hugos','Novella',6,'This Census-Taker','by China Miéville (Del Rey / Picador)'),
('Hugos','Novelette',1,'Alien Stripper Boned From Behind By The T-Rex','by Stix Hiscock (self-published)'),
('Hugos','Novelette',2,'"The Art of Space Travel"','by Nina Allan (Tor.com, July 2016)'),
('Hugos','Novelette',3,'The Jewel and Her Lapidary','by Fran Wilde (Tor.com publishing, May 2016)'),
('Hugos','Novelette',4,'"The Tomato Thief"','by Ursula Vernon (Apex Magazine, January 2016)'),
('Hugos','Novelette',5,'"Touring with the Alien"','by Carolyn Ives Gilman (Clarkesworld Magazine, April 2016)'),
('Hugos','Novelette',6,'"You''ll Surely Drown Here If You Stay"','by Alyssa Wong (Uncanny Magazine, May 2016)'),
('Hugos','ShortStory',1,'"The City Born Great"','by N. K. Jemisin (Tor.com, September 2016)'),
('Hugos','ShortStory',2,'"A Fist of Permutations in Lightning and Wildflowers"','by Alyssa Wong (Tor.com, March 2016)'),
('Hugos','ShortStory',3,'"Our Talons Can Crush Galaxies"','by Brooke Bolander (Uncanny Magazine, November 2016)'),
('Hugos','ShortStory',4,'"Seasons of Glass and Iron"','by Amal El-Mohtar (The Starlit Wood: New Fairy Tales, Saga Press)'),
('Hugos','ShortStory',5,'"That Game We Played During the War"','by Carrie Vaughn (Tor.com, March 2016)'),
('Hugos','ShortStory',6,'"An Unimaginable Light"','by John C. Wright (God, Robot, Castalia House)'),
('Hugos','RelatedWork',1,'The Geek Feminist Revolution','by Kameron Hurley (Tor Books)'),
('Hugos','RelatedWork',2,'The Princess Diarist','by Carrie Fisher (Blue Rider Press)'),
('Hugos','RelatedWork',3,'Traveler of Worlds: Conversations with Robert Silverberg','by Robert Silverberg and Alvaro Zinos-Amaro (Fairwood)'),
('Hugos','RelatedWork',4,'The View From the Cheap Seats','by Neil Gaiman (William Morrow / Harper Collins)'),
('Hugos','RelatedWork',5,'The Women of Harry Potter posts','by Sarah Gailey (Tor.com)'),
('Hugos','RelatedWork',6,'Words Are My Matter: Writings About Life and Books, 2000-2016','by Ursula K. Le Guin (Small Beer)'),
('Hugos','GraphicStory',1,'Black Panther, Volume 1: A Nation Under Our Feet','written by Ta-Nehisi Coates, illustrated by Brian Stelfreeze (Marvel)'),
('Hugos','GraphicStory',2,'Monstress, Volume 1: Awakening','written by Marjorie Liu, illustrated by Sana Takeda (Image)'),
('Hugos','GraphicStory',3,'Ms. Marvel, Volume 5: Super Famous','written by G. Willow Wilson, illustrated by Takeshi Miyazawa (Marvel)'),
('Hugos','GraphicStory',4,'Paper Girls, Volume 1','written by Brian K. Vaughan, illustrated by Cliff Chiang, colored by Matthew Wilson, lettered by Jared Fletcher (Image)'),
('Hugos','GraphicStory',5,'Saga, Volume 6','illustrated by Fiona Staples, written by Brian K. Vaughan, lettered by Fonografiks (Image)'),
('Hugos','GraphicStory',6,'The Vision, Volume 1: Little Worse Than A Man','written by Tom King, illustrated by Gabriel Hernandez Walta (Marvel)'),
('Hugos','DramaticLong',1,'Arrival','screenplay by Eric Heisserer based on a short story by Ted Chiang, directed by Denis Villeneuve (21 Laps Entertainment/FilmNation Entertainment/Lava Bear Films)'),
('Hugos','DramaticLong',2,'Deadpool','screenplay by Rhett Reese & Paul Wernick, directed by Tim Miller (Twentieth Century Fox Film Corporation/Marvel Entertainment/Kinberg Genre/The Donners'' Company/TSG Entertainment)'),
('Hugos','DramaticLong',3,'Ghostbusters','screenplay by Katie Dippold & Paul Feig, directed by Paul Feig (Columbia Pictures/LStar Capital/Village Roadshow Pictures/Pascal Pictures/Feigco Entertainment/Ghostcorps/The Montecito Picture Company)'),
('Hugos','DramaticLong',4,'Hidden Figures','screenplay by Allison Schroeder	and Theodore Melfi, directed by Theodore Melfi (Fox 2000 Pictures/Chernin Entertainment/Levantine Films/TSG Entertainment)'),
('Hugos','DramaticLong',5,'Rogue One','screenplay by Chris Weitz and Tony Gilroy, directed by Gareth Edwards (Lucasfilm/Allison Shearmur Productions/Black Hangar Studios/Stereo D/Walt Disney Pictures)'),
('Hugos','DramaticLong',6,'Stranger Things, Season One','created by the Duffer Brothers (21 Laps Entertainment/Monkey Massacre)'),
('Hugos','DramaticShort',1,'Black Mirror: "San Junipero"','written by Charlie Brooker, directed by Owen Harris (House of Tomorrow)'),
('Hugos','DramaticShort',2,'Doctor Who: "The Return of Doctor Mysterio"','written by Steven Moffat, directed by Ed Bazalgette (BBC Cymru Wales)'),
('Hugos','DramaticShort',3,'The Expanse: "Leviathan Wakes"','written by Mark Fergus and Hawk Ostby, directed by Terry McDonough (SyFy)'),
('Hugos','DramaticShort',4,'Game of Thrones: "Battle of the Bastards"','written by David Benioff and D. B. Weiss, directed by Miguel Sapochnik (HBO)'),
('Hugos','DramaticShort',5,'Game of Thrones: "The Door"','written by David Benioff and D. B. Weiss, directed by Jack Bender (HBO)'),
('Hugos','DramaticShort',6,'Splendor & Misery [album]','by Clipping (Daveed Diggs, William Hutson, Jonathan Snipes)'),
('Hugos','EditorShort',1,'John Joseph Adams',null),
('Hugos','EditorShort',2,'Neil Clarke',null),
('Hugos','EditorShort',3,'Ellen Datlow',null),
('Hugos','EditorShort',4,'Jonathan Strahan',null),
('Hugos','EditorShort',5,'Lynne M. Thomas & Michael Damian Thomas',null),
('Hugos','EditorShort',6,'Sheila Williams',null),
('Hugos','EditorLong',1,'Vox Day',null),
('Hugos','EditorLong',2,'Sheila E. Gilbert',null),
('Hugos','EditorLong',3,'Liz Gorinsky',null),
('Hugos','EditorLong',4,'Devi Pillai',null),
('Hugos','EditorLong',5,'Miriam Weinberg',null),
('Hugos','EditorLong',6,'Navah Wolfe',null),
('Hugos','ProArtist',1,'Galen Dara',null),
('Hugos','ProArtist',2,'Julie Dillon',null),
('Hugos','ProArtist',3,'Chris McGrath',null),
('Hugos','ProArtist',4,'Victo Ngai',null),
('Hugos','ProArtist',5,'John Picacio',null),
('Hugos','ProArtist',6,'Sana Takeda',null),
('Hugos','Semiprozine',1,'Beneath Ceaseless Skies','editor-in-chief and publisher Scott H. Andrews'),
('Hugos','Semiprozine',2,'Cirsova Heroic Fantasy and Science Fiction Magazine','edited by P. Alexander'),
('Hugos','Semiprozine',3,'GigaNotoSaurus','edited by Rashida J. Smith'),
('Hugos','Semiprozine',4,'Strange Horizons','edited by Niall Harrison, Catherine Krahe, Vajra Chandrasekera, Vanessa Rose Phin, Li Chua, Aishwarya Subramanian, Tim Moore, Anaea Lay, and the Strange Horizons staff'),
('Hugos','Semiprozine',5,'Uncanny Magazine','edited by Lynne M. Thomas & Michael Damian Thomas, Michi Trota, Julia Rios, and podcast produced by Erika Ensign & Steven Schapansky'),
('Hugos','Semiprozine',6,'The Book Smugglers','edited by Ana Grilo and Thea James'),
('Hugos','Fanzine',1,'Castalia House Blog','edited by Jeffro Johnson'),
('Hugos','Fanzine',2,'Journey Planet','edited by James Bacon, Chris Garcia, Esther MacCallum-Stewart, Helena Nash, Errick Nunnally, Pádraig Ó Méalóid, Chuck Serface, and Erin Underwood'),
('Hugos','Fanzine',3,'Lady Business','edited by Clare, Ira, Jodie, KJ, Renay, and Susan'),
('Hugos','Fanzine',4,'nerds of a feather, flock together','edited by The G, Vance Kotrla, and Joe Sherry'),
('Hugos','Fanzine',5,'Rocket Stack Rank','edited by Greg Hullender and Eric Wong'),
('Hugos','Fanzine',6,'SF Bluestocking','edited by Bridget McKinney'),
('Hugos','Fancast',1,'The Coode Street Podcast','presented by Gary K. Wolfe and Jonathan Strahan'),
('Hugos','Fancast',2,'Ditch Diggers','presented by Mur Lafferty and Matt Wallace'),
('Hugos','Fancast',3,'Fangirl Happy Hour','presented by Ana Grilo and Renay Williams'),
('Hugos','Fancast',4,'Galactic Suburbia','presented by Alisa Krasnostein, Alexandra Pierce and Tansy Rayner Roberts, produced by Andrew Finch'),
('Hugos','Fancast',5,'The Rageaholic','presented by RazörFist'),
('Hugos','Fancast',6,'Tea and Jeopardy','presented by Emma Newman with Peter Newman'),
('Hugos','FanWriter',1,'Mike Glyer',null),
('Hugos','FanWriter',2,'Jeffro Johnson',null),
('Hugos','FanWriter',3,'Natalie Luhrs',null),
('Hugos','FanWriter',4,'Foz Meadows',null),
('Hugos','FanWriter',5,'Abigail Nussbaum',null),
('Hugos','FanWriter',6,'Chuck Tingle',null),
('Hugos','FanArtist',1,'Ninni Aalto',null),
('Hugos','FanArtist',2,'Vesa Lehtimäki',null),
('Hugos','FanArtist',3,'Likhain (M. Sereno)',null),
('Hugos','FanArtist',4,'Spring Schoenhuth',null),
('Hugos','FanArtist',5,'Steve Stiles',null),
('Hugos','FanArtist',6,'Mansik Yang',null),
('Hugos','Series',1,'The Craft Sequence','by Max Gladstone (Tor Books)'),
('Hugos','Series',2,'The Expanse','by James S.A. Corey (Orbit US / Orbit UK)'),
('Hugos','Series',3,'The October Daye Books','by Seanan McGuire (DAW / Corsair)'),
('Hugos','Series',4,'The Peter Grant / Rivers of London series','by Ben Aaronovitch (Gollancz / Del Rey / DAW / Subterranean)'),
('Hugos','Series',5,'The Temeraire series','by Naomi Novik (Del Rey / Harper Voyager UK)'),
('Hugos','Series',6,'The Vorkosigan Saga','by Lois McMaster Bujold (Baen)'),
('Hugos','NewWriter',1,'Sarah Gailey','1st year of eligibility'),
('Hugos','NewWriter',2,'J. Mulrooney','1st year of eligibility'),
('Hugos','NewWriter',3,'Malka Older','2nd year of eligibility'),
('Hugos','NewWriter',4,'Ada Palmer','1st year of eligibility'),
('Hugos','NewWriter',5,'Laurie Penny','2nd year of eligibility'),
('Hugos','NewWriter',6,'Kelly Robson','2nd year of eligibility');
